# Generated by Django 4.1.3 on 2022-11-18 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)])),
                ('category', models.CharField(choices=[('Soup', 'Soup'), ('Dessert', 'Dessert'), ('Snack', 'Snack'), ('Salad', 'Salad'), ('Baked', 'Baked'), ('Main', 'Main'), ('Pizza', 'Pizza'), ('Others', 'Others')], default='Others', max_length=7)),
                ('photo', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('ingredients', models.TextField()),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('time_in_minutes', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
